In [ ]:
#1

from matplotlib.pyplot import*
from numpy import*
import sympy as sp
#1
arr = matrix('-1 4;-5 2')
detA = linalg.det(arr)
#2
a,b = sp.symbols('a b')
arr2 = sp.Matrix([[a+b,a-b],[a+b,a-b]])
detA2 = sp.det(arr2)
#3 
x = sp.symbols('x')
arr3 = sp.Matrix([[x,x+1],[-4,x+1]])
detA3 = sp.det(arr3)

print(detA)
print(detA2)
print(sp.factor(detA3))

17.999999999999996
0
(x + 1)*(x + 4)


In [13]:
#2

import sympy as sp
import numpy as np
#1
arr1 = matrix('1 2 3;4 5 6;7 8 1')
detA = linalg.det(arr1)
#2 
a,x,c = sp.symbols('a x c')
arr2 = sp.Matrix([[a+x,x,x],[x,b+x,x],[x,x,c+x]])
detA2 = sp.det(arr2)
#3 
a ,b,c = sp.symbols('a b c')
arr3 = sp.Matrix([[sp.sin(a),sp.cos(b),1],[sp.sin(b),sp.cos(b),1],[sp.sin(c),sp.cos(c),1]])
detA3 = sp.det(arr3)



print(detA)
print(detA2)
print(sp.simplify(detA3))


23.999999999999993
a*b*c + a*b*x + a*c*x + b*c*x
sin(a)*cos(b) - sin(a)*cos(c) + sin(b)*cos(c) - sin(2*b)/2


In [ ]:
#3.1

from numpy import*
import sympy as sp
A = matrix('3 -5;2 7')
B = matrix('13;81')
A_det = linalg.det(A)
X_m = matrix(A)
X_m[:, 0] = B
Y_m = matrix(A)
Y_m[:, 1] = B
x = linalg.det(X_m) / A_det
y = linalg.det(Y_m) / A_det
X = sp.Matrix([[x],[y]])
print(dot(A,X) - B)
print(x,y)

[[1.42108547152020e-14]
 [2.84217094304040e-14]]
16.000000000000007 7.000000000000001


In [31]:
#3.2

from numpy import*
import sympy as sp
A = matrix('3 -4;-6 8')
B = matrix('-6;12')
A_det = linalg.det(A)
print(A_det)


0.0


In [33]:
#3.3

from numpy import*
import sympy as sp
A = matrix('7 2 3;5 -3 2;10 -11 5')
B = matrix('15;15;36')
A_det = linalg.det(A)
X_m = matrix(A)
X_m[:, 0] = B
Y_m = matrix(A)
Y_m[:, 1] = B
Z_m = matrix(A)
Z_m[:,2] = B
x = linalg.det(X_m) / A_det
y = linalg.det(Y_m) / A_det
z = linalg.det(Z_m) / A_det
X = sp.Matrix([[x],[y]])
print(x,y,z)

1.9999999999999984 -1.0 0.999999999999999


In [34]:
#3.4

from numpy import*
import sympy as sp
A = matrix('2 1 0;1 0 3;0 5 -1')
B = matrix('5;16;10')
A_det = linalg.det(A)
X_m = matrix(A)
X_m[:, 0] = B
Y_m = matrix(A)
Y_m[:, 1] = B
Z_m = matrix(A)
Z_m[:,2] = B
x = linalg.det(X_m) / A_det
y = linalg.det(Y_m) / A_det
z = linalg.det(Z_m) / A_det
X = sp.Matrix([[x],[y]])
print(x,y,z)

1.0 3.000000000000001 5.000000000000001


In [ ]:
#4.1
import numpy as np
import sympy as sp

A = np.matrix('3 -5;2 7')
B = np.matrix('13;81')
A_inv = np.linalg.inv(A)
print(A_inv*B)



[[16.]
 [ 7.]]


In [36]:
#4.2

from numpy import*
import sympy as sp
A = matrix('7 2 3;5 -3 2;10 -11 5')
B = matrix('15;15;36')
A_inv = linalg.inv(A)
print(A_inv*B)

[[ 2.]
 [-1.]
 [ 1.]]


In [44]:
#5.1
from numpy import*

A = matrix('3 -5;2 7')
B = matrix('13;81')
X = matrix('16;7')
print(A*X - B == 0)

[[ True]
 [ True]]


In [46]:
#5.2

from numpy import*
import sympy as sp
A = matrix('7 2 3;5 -3 2;10 -11 5')
B = matrix('15;15;36')
X = matrix('2;-1;1')
print(A*X-B==0)

[[ True]
 [ True]
 [ True]]


In [49]:
#6
from numpy import*
A = matrix('0.1 0.5 0.02;0.3 0.9 0;0.7 0.2 0.5')
B = matrix('586;1095;2560')
A_inv = A**-1
print(A_inv*B)

[[1250.]
 [ 800.]
 [3050.]]
